### ISSUE TITLE
Error running the script - Division Zero and module

### ISSUE THREAD

**Issue by aandraa** [Dmitry-Zh01/zabbix-sla-report#1]
Exception: division by zero

Traceback (most recent call last):
  File "sla_report.py", line 225, in <module>
    ws2.append([prb[pr]['hosts'][0]['host']] + [int(prb[pr]['eventid'])] + [prb[pr]['name']] + [dt.fromtimestamp(int(prb[pr]['clock'])).strftime('%Y-%m-%d %H:%M:%S')] + [int(res[pr]['eventid'])] + [dt.fromtimestamp(int(res[pr]['clock'])).strftime('%Y-%m-%d %H:%M:%S')])

**Comment by Dmitry-Zh01** [comment]
Hello.

Probably, this issue is related to inexistance of Zabbix item key "icmpping[,5]" for selected host or hostgroup added to the script by default.
Please, try to use updated script.
- Added default item key "icmpping"
- Added -K argument to choose items to use
- Added additional check while executing the script. If the item is not represented for host or hostgroup - this will be printed in the terminal.

Best regards,
Dmitry.
